name: Terraform CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'terraform/**'

env:
  TF_ROOT: terraform
  OS_AUTH_URL: "https://msk.cloud.vk.com/infra/identity/v3/"
  OS_USERNAME: "souluna050@gmail.com"
  OS_PASSWORD: ${{ secrets.VK_PASSWORD }}
  OS_PROJECT_ID: "92cbb98bb6e445a7b83c7ba436d22b1a"
  OS_DOMAIN_NAME: "users"
  OS_REGION_NAME: "RegionOne"
  TF_VAR_my_ip: ${{ secrets.TF_VAR_my_ip }}
  TF_VAR_project_name: "cicd-demo"

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
      - name: Terraform Init
        run: cd $TF_ROOT && terraform init
      - name: Terraform Validate
        run: cd $TF_ROOT && terraform validate

  plan:
    name: Plan
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
      - name: Terraform Init
        run: cd $TF_ROOT && terraform init
      - name: Terraform Plan
        run: cd $TF_ROOT && terraform plan -no-color

  apply:
    name: Apply
    runs-on: ubuntu-latest
    needs: plan
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
      - name: Terraform Init
        run: cd $TF_ROOT && terraform init
      - name: Terraform Apply
        run: cd $TF_ROOT && terraform apply -auto-approve
